name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Installing Dependencies
      run: make install_dep
    
    - name: Beautify
      run: make beautify
    
    - name: Commit those back
      uses: EndBug/add-and-commit@v7.5.0
      with:
        message: "Beautified"
        author_name: "Code beautifier"
